### ISSUE TITLE
Can't install SVDQuant in ComfyUI.

### ISSUE THREAD

**Issue by KurosuYus** [mit-han-lab/nunchaku#104]
I am unable to install SVDQuant in ComfyUI Manager, even if I import the workflow first and then search for the missing nodes.

**Comment by igs-kumayu** [comment]
[Installation Errors]
'svdquant': With the current security level configuration, only custom nodes from the "default channel" can be installed.

**Comment by judian17** [comment]
I'm sorry, I don't know how to reference an issue on GitHub. What I mean is that you can refer to this issue:https://github.com/mit-han-lab/nunchaku/issues/57

**Comment by lmxyy** [comment]
I will look at your issue later today.

**Comment by lmxyy** [comment]
The security issue should be resolved. I am not sure if this will pop out again tomorrow. The [linux wheels](https://github.com/mit-han-lab/nunchaku?tab=readme-ov-file#wheels-linux-only-for-now) have been released. I am now looking into windows support.

**Comment by Ainierheokami** [comment]
I'm encountering a similar issue with SVDQuant in WSL:

1. Direct installation via comfyui-manage: Loading SVDQuant fails.
2. Manual installation:
```
2025-02-26 10:50:39 Traceback (most recent call last):
2025-02-26 10:50:39   File "/workspace/ComfyUI/nodes.py", line 2145, in load_custom_node
2025-02-26 10:50:39     module_spec.loader.exec_module(module)
2025-02-26 10:50:39   File "<frozen importlib._bootstrap_external="">", line 995, in exec_module
2025-02-26 10:50:39   File "<frozen importlib._bootstrap="">", line 488, in _call_with_frames_removed
2025-02-26 10:50:39   File "/workspace/ComfyUI/custom_nodes/svdquant/__init__.py", line 3, in <module>
2025-02-26 10:50:39     from .nodes.lora import SVDQuantFluxLoraLoader
2025-02-26 10:50:39   File "/workspace/ComfyUI/custom_nodes/svdquant/nodes/lora/__init__.py", line 1, in <module>
2025-02-26 10:50:39     from .flux import SVDQuantFluxLoraLoader
2025-02-26 10:50:39   File "/workspace/ComfyUI/custom_nodes/svdquant/nodes/lora/flux.py", line 7, in <module>
2025-02-26 10:50:39     from nunchaku.lora.flux.comfyui_converter import comfyui2diffusers
2025-02-26 10:50:39 ModuleNotFoundError: No module named 'nunchaku'
```
Attempting `pip install nunchaku` does not resolve the issue.

**Comment by lmxyy** [comment]
> I'm encountering a similar issue with SVDQuant in WSL:
> 
> 1. Direct installation via comfyui-manage: Loading SVDQuant fails.
> 2. Manual installation:
> 
> ```
> 2025-02-26 10:50:39 Traceback (most recent call last):
> 2025-02-26 10:50:39   File "/workspace/ComfyUI/nodes.py", line 2145, in load_custom_node
> 2025-02-26 10:50:39     module_spec.loader.exec_module(module)
> 2025-02-26 10:50:39   File "<frozen importlib._bootstrap_external="">", line 995, in exec_module
> 2025-02-26 10:50:39   File "<frozen importlib._bootstrap="">", line 488, in _call_with_frames_removed
> 2025-02-26 10:50:39   File "/workspace/ComfyUI/custom_nodes/svdquant/__init__.py", line 3, in <module>
> 2025-02-26 10:50:39     from .nodes.lora import SVDQuantFluxLoraLoader
> 2025-02-26 10:50:39   File "/workspace/ComfyUI/custom_nodes/svdquant/nodes/lora/__init__.py", line 1, in <module>
> 2025-02-26 10:50:39     from .flux import SVDQuantFluxLoraLoader
> 2025-02-26 10:50:39   File "/workspace/ComfyUI/custom_nodes/svdquant/nodes/lora/flux.py", line 7, in <module>
> 2025-02-26 10:50:39     from nunchaku.lora.flux.comfyui_converter import comfyui2diffusers
> 2025-02-26 10:50:39 ModuleNotFoundError: No module named 'nunchaku'
> ```
> 
> Attempting `pip install nunchaku` does not resolve the issue.

Please do not use `pip install nunchaku`. This is not our package.

**Comment by KurosuYus** [comment]
> First, you need to download Nunchaku on Windows. You can refer to #issue57 for downloading it. After making sure you have downloaded it, you can use the command `cd E:\comfyui\ComfyUI-aki-v1.3\custom_nodes` (replace the path before custom_nodes with your ComfyUI path, i.e., navigate to your custom_nodes folder). Then, use the command `mklink /d svdquant E:\comfyui\ComfyUI-aki-v1.3\python11\nunchaku\comfyui`, where `nunchaku\comfyui` comes from Nunchaku.In addition, I found that directly installing Nunchaku in ComfyUI's Python environment failed to compile successfully (at least for me). However, if you first create a virtual environment using Conda, and then use the `python.exe` from ComfyUI's environment within that virtual environment to install Nunchaku, it will succeed. For example: (D:\0AI\0StableDiffusion\ComfyUI\python_embeded\python.exe -m pip install --no-build-isolation -e .)

I am also using Aki's integrated package, and I successfully compiled Nunchaku using your method. Running `python -m nunchaku.test` did not show any errors. However, when I open ComfyUI, it still displays:
```
0.0 seconds (IMPORT FAILED): E:\Github\016-ComfyUI\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\nunchaku
0.0 seconds (IMPORT FAILED): E:\Github\016-ComfyUI\ComfyUI-aki-v1.6\ComfyUI\custom_nodes\svdquant
```

**Comment by KurosuYus** [comment]
> which error did you meet? did you install nunchaku?

Actually, the main issue is that I can't find the svdquant node in the ComfyUI Manager. Initially, I thought it was because Nunchaku wasn't installed, but now that I've installed it, it seems that the problem isn't related to Nunchaku after all?

**Comment by judian17** [comment]
@KurosuYus There should be additional information in the logs regarding the failed import of svdquant, which might indicate the reason for the failure. Could you provide more details or the complete log file? Additionally, after downloading nunchaku, you need to execute the following code to successfully import the cmfyui node: `python -m pip install git+https://github.com/asomoza/image_gen_aux.git`

**Comment by fangg2000** [comment]
mybe you can try just like this:
    # nunchaku环境安装
    conda create --prefix "/home/fangg/anaconda3/envs/nun7" python=3.11.4
    pip install ninja wheel diffusers transformers accelerate sentencepiece protobuf huggingface_hub
    pip install peft opencv-python gradio spaces GPUtil
    pip install https://huggingface.co/mit-han-lab/nunchaku/resolve/main/nunchaku-0.1.3+torch2.5-cp311-cp311-linux_x86_64.whl
    
    # nunchaku包安装
    git clone https://github.com/mit-han-lab/nunchaku.git
    cd nunchaku
    git submodule init
    git submodule update

    # comfyui svdquant节点安装及配置
    pip install git+https://github.com/asomoza/image_gen_aux.git
    cd custom_nodes
    ln -s ../../nunchaku/comfyui svdquant

    cd ComfyUI
    pip install -r requirements.txt

**Comment by fangg2000** [comment]
The entire execution is normal and the image can be produced, but there are some other problems on my computer.

**Comment by lmxyy** [comment]
I think the installation issue should be resolved. I will close this issue. Feel free to open a new one if you have other questions.

**Comment by lmxyy** [comment]
> The entire execution is normal and the image can be produced, but there are some other problems on my computer.

I think your issue is similar to #139 #61 #59 #49 #22  We are rooting the causes for these issues.
