### ISSUE TITLE
Failed to load safetensors using method MIO and  3d torch.Tensor is deprecated.

### ISSUE THREAD

**Issue by one903045** [mit-han-lab/nunchaku#208]
![Image](https://github.com/user-attachments/assets/819b27e3-0024-4b3f-b308-a6c1eeec39ce)
deepcompressor           0.0.1
image_gen_aux            0.1.0.dev0
image-reward             1.5
nunchaku                 0.1.4+torch2.6
--------------------------------------------------------------------------------------------------
I can complete the sampling and output of images, but I don't feel any acceleration, 4 steps is Blurred and terrible.
my GPU is 3090，CUDA is 12.6，WIN10，torch2.6、python12.9 version use nunchaku-0.1.4+torch2.6-cp312-cp312-win_amd64.whl to  compile Successfully.
And Another issue is batch can't more than 1.

**Comment by lmxyy** [comment]
The latest release of [nunchaku node v0.1.6](https://github.com/mit-han-lab/ComfyUI-nunchaku) in [our new repo](https://github.com/mit-han-lab/ComfyUI-nunchaku) should resolve the 3D tensor issue. Please disable the CPU offloading on your GPUs. Currently, we only support batch size of 1. Larger batch inference will be supported in the later version. Could you send us your generated images for debugging?

**Comment by one903045** [comment]
> The latest release of [nunchaku node v0.1.6](https://github.com/mit-han-lab/ComfyUI-nunchaku) in [our new repo](https://github.com/mit-han-lab/ComfyUI-nunchaku) should resolve the 3D tensor issue. Please disable the CPU offloading on your GPUs. Currently, we only support batch size of 1. Larger batch inference will be supported in the later version. Could you send us your generated images for debugging?

Oh!It‘my  misunderstood，dev is Normaly accelerate by multiple steps。Maybe 4 steps need shnell？And [warnign] Failed to load safetensors is still exist.  

(i use ComfyUI-nunchaku node v0.1.6 )

When I use Shnell int4

![Image](https://github.com/user-attachments/assets/582cca60-7585-4ff0-9bf9-b6a357d9d335)

![Image](https://github.com/user-attachments/assets/c23c34d8-9fa3-4af0-8561-f007199668bf)

When I use Shnell fp4

![Image](https://github.com/user-attachments/assets/295cbd9e-8324-414c-8350-df36d2486645)

When I use shuttle yaguar int4 

![Image](https://github.com/user-attachments/assets/684c84ff-16af-4542-b51c-088374f251f9)

![Image](https://github.com/user-attachments/assets/083432cb-5efc-4cd8-b832-cba8dc7f7f30)

I uninstall nunchaku（use whl） and try to compile by myself, but failed in PYthon11 or 12，WIN10.

**Comment by lmxyy** [comment]
Could you try our walkaround in the [FAQ](https://github.com/mit-han-lab/nunchaku/blob/main/docs/faq.md#out-of-memory-or-slow-model-loading-egmit-han-labnunchaku249-mit-han-labnunchaku311-mit-han-labnunchaku276)? 

<img width="1182" alt="Image" src="https://github.com/user-attachments/assets/beda4ab4-7d8d-4ca9-add7-dc1572259a63" />
